# name: Build

# on:
#   push:
#     branches:
#       - main
#       - dev
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         working-directory: ./frontend
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           npm install  # Install frontend dependencies

#       - name: Have App running
#         working-directory: ./frontend
#         run: |
#           npm install
#           nohup npm start &
#           sleep 5

#       - name: Run Coverage for Behave Tests
#         working-directory: ./frontend
#         run: |
#           coverage run -m behave tests/LandingPage
#           coverage xml  # Generate coverage.xml for SonarCloud

#   sonarcloud:
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     needs: test  # Wait for the 'test' job to finish
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Install dependencies for SonarCloud
#         working-directory: ./frontend
#         run: |
#           python -m pip install coverage  # Install coverage in Sonar job if needed
#           pip install -r requirements.txt
#           npm install

#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.projectBaseDir=./frontend
#             -Dsonar.python.coverage.reportPaths=frontend/coverage.xml